#pragma config(Sensor, S1,     leftBumper,          sensorTouch)
#pragma config(Sensor, S2,     rightBumper,         sensorTouch)
#pragma config(Sensor, S3,     leftLight,           sensorLightInactive)
#pragma config(Sensor, S4,     rightLight,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "course.h"
//left is A, right is B
int courseState = 0;

task main()
{
  StartTask(course);
  while(true){}
}

task course()
{
  //first task
  //StartTask(seek);
  while (true)
  {

    //light found
    //state 1
    //go forward
    if(facingLight)
    {
      newTask(1);
    }
    //base - lood for light
    //state 0
	  else
	  {
	    newTask(0);
	  }

  }
}

void newCourseTask(int newT)
{
  if (courseState != newT)
  {
    stopCurrentTask(courseState);
    courseState = newT;
	  switch(newT){
    case 1:
      StartTask(avoid_obstacles);
      break;
    case 0:
      StartTask(towards_light);
      break;
    }
  }
}

void stopCurrentCourseTask(int oldT)
{
  switch(oldT){
    case 1:
      StopTask(avoid_obstacles);
      break;
    case 0:
      StopTask(towards_light);
      break;
  }
}
