#pragma config(Sensor, S1,     leftBumper,          sensorTouch)
#pragma config(Sensor, S2,     rightBumper,         sensorTouch)
#pragma config(Sensor, S3,     leftLight,           sensorLightInactive)
#pragma config(Sensor, S4,     rightLight,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "course.h"
//left is A, right is B

const float bright_light = 25;
int currentState = 0;

task main()
{
  StartTask(course);
  while(true){}
}

task course()
{
  //first task
  //StartTask(seek);
  while (true)
  {

    //light found
    //state 1
    //go forward
    if((SensorValue(leftLight) > bright_light) || (SensorValue(rightLight) > bright_light))
    {
      newTask(1);
    }
    //base - lood for light
    //state 0
	  else
	  {
	    newTask(0);
	  }

  }
}

void newTask(int newT)
{
  if (currentState != newT)
  {
    stopCurrentTask(currentState);
    currentState = newT;
	  switch(newT){
    case 1:
      StartTask(approach_light);
      break;
    case 0:
      StartTask(seek);
      break;
    }
  }
}

void stopCurrentTask(int oldT)
{
  switch(oldT){
    case 1:
      StopTask(approach_light);
      break;
    case 0:
      StopTask(seek);
      break;
  }
}
