#pragma config(Sensor, S1,     sonarSensor,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displaySonarValue()
{
	nxtDisplayCenteredTextLine(3, "Value: %d", SensorValue[sonarSensor]);
	wait1Msec(1000);
}

task main()
{
	while(1)
	{
		displaySonarValue();
	}
}
