#pragma config(Sensor, S1,     sonar,               sensorSONAR)
#pragma config(Sensor, S2,     light,               sensorLightActive)
#pragma config(Motor,  motorA,          left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          sonarMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displaySonarValue()
{
	nxtDisplayCenteredTextLine(3, "Value: %d", SensorValue[S2]);
	wait1Msec(1000);
}

task main()
{
	while(1)
	{
		displaySonarValue();
	}
}
