#pragma config(Sensor, S1,     sonar,               sensorSONAR)
#pragma config(Sensor, S2,     light,               sensorLightActive)
#pragma config(Motor,  motorA,          left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          sonarMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
const float ENC_P_CM = 21.157;

void sonarTo(int degrees)
{
  degrees = - degrees;
  const int speed = 20;
  int difference = nMotorEncoder[motorC] - degrees;

  if (difference < 0)
  {
    motor[motorC] = speed;
    while(nMotorEncoder[motorC] < degrees)
      ;
  } else {
    motor[motorC] = -speed;
    while(nMotorEncoder[motorC] > degrees)
      ;
  }
  motor[motorC] = 0;
  wait1Msec(500);

}

task shake_head()
{
  while(true)
  {
    sonarTo(-10);
    wait1Msec(100);
    sonarTo(10);
    wait1Msec(100);
  }
}

void follow_outer_wall()
{
  int balance = 0;
  int reading = SensorValue[S1];
  int oldReading = SensorValue[S1];

  const int wall_follow_distance = 20;
  const float volatility = 1.5;
  const int drive_power = 20;
  const int base = 12;

  nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
  motor[motorA] = drive_power;
  motor[motorB] = drive_power;

  while(SensorValue[S2] < 30)
  {

    reading = SensorValue[S1];
    nxtDisplayCenteredTextLine(1, "reading: %d", reading);

    if(reading < 100)
    {
      balance = volatility*(SensorValue[S1] - wall_follow_distance);
    } else {
      if (balance < 0 && oldReading > wall_follow_distance || balance > 0 && oldReading < wall_follow_distance)
      {
        balance = -base;
      } else {
        balance = base;
      }
    }

    nxtDisplayCenteredTextLine(2, "bal: %d", balance);
    motor[motorA] = drive_power - balance;
    motor[motorB] = drive_power + balance;
    oldReading = reading;
  }
}

task main(){
 follow_outer_wall();
}
