#pragma config(Sensor, S1,     sonar,               sensorSONAR)
#pragma config(Sensor, S2,     bump,                sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          sonarMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//
const float ENC_P_CM = 21.157;
const int drive_power = 20;
const int wall_distance = 20;
const float damper = 1;

void follow_wall(int distance)
{
  float balance = 0;

  nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;

  float lineStart = nMotorEncoder[motorA];
  float encoderLimit = ENC_P_CM*distance;

  while((nMotorEncoder[motorA] - lineStart) < encoderLimit)
  {
    balance = damper*(SensorValue[S1] - wall_distance);
    motor[motorA] = drive_power - balance;
    motor[motorB] = drive_power + balance;
  }

  motor[motorA] = 0;
  motor[motorB] = 0;

}

task main()
{

  nMotorEncoder[motorC] = 0;


  //Turn the sonar left.
  motor[motorC] = 20;
  while(nMotorEncoder[motorC] < 90)
    ;
  motor[motorC] = 0;

  follow_wall(1000);


  //fix and return
  motor[motorC] = -20;
  while(nMotorEncoder[motorC] > 0)
    ;
  motor[motorC] = 0;

}
