#pragma config(Sensor, S1,     leftBumper,          sensorTouch)
#pragma config(Sensor, S2,     rightBumper,         sensorTouch)
#pragma config(Sensor, S3,     leftLight,           sensorLightInactive)
#pragma config(Sensor, S4,     rightLight,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "obstacles.h"
//left is A, right is B

task main()
{
  StartTask(avoid_obstacles);
  while(true){}
}

task avoid_obstacles()
{
  int currentState;

  while (true)
  {

    //hit
    //state 1
    if(SensorValue(leftBumper) || SensorValue(rightBumper))
    {
      if (currentState != 1)
      {
        stopCurrentTask(currentState);
      }
      currentState = 1;
      StartTask(reverseCorner);
    }
    //base
    //state 0
	  else
	  {
	    if (currentState != 0)
      {
        stopCurrentTask(currentState);
      }
	    currentState = 0;
	    StartTask(moveForward);
	  }

  }
}

void stopCurrentTask(int t)
{
  switch(t){
    case 1:
      StopTask(reverseCorner);
    case 0:
      StopTask(moveForward);
  }

}

task moveForward()
{
  int speed = 30;
  nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
  motor[motorA] = speed;
  motor[motorB] = speed;
}

task reverseCorner()
{
  int left = SensorValue(leftBumper);
  int speed = -50;
  int ratio = 30;
  if (left)
  {
    nSyncedMotors = synchBA;
    nSyncedTurnRatio = ratio;
    motor[motorB] = speed;
  } else {
    nSyncedMotors = synchAB;
    nSyncedTurnRatio = ratio;
    motor[motorA] = speed;
  }
}
