#ifndef SENSORS_H
#define SENSORS_H

#pragma config(Sensor, S1,     leftBumper,          sensorTouch)
#pragma config(Sensor, S2,     rightBumper,         sensorTouch)
#pragma config(Sensor, S3,     leftLight,           sensorLightInactive)
#pragma config(Sensor, S4,     rightLight,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#endif
