#pragma config(Sensor, S1,     leftBumper,          sensorTouch)
#pragma config(Sensor, S2,     rightBumper,         sensorTouch)
#pragma config(Sensor, S3,     leftLight,           sensorLightInactive)
#pragma config(Sensor, S4,     rightLight,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "towards_light.h"
//left is A, right is B

const float bright_light = 25;
int currentState = 0;

task main()
{
  StartTask(towards_light);
  while(true){}
}

task towards_light()
{
  StartTask(seek);
  while (true)
  {

    //light found
    //state 1
    if((SensorValue(leftLight) > bright_light) || (SensorValue(rightLight) > bright_light))
    {
      newTask(1);
    }
    //base
    //state 0
	  else
	  {
	    newTask(0);
	  }

  }
}

void newTask(int newT)
{
  if (currentState != newT)
  {
    stopCurrentTask(currentState);
    currentState = newT;
	  switch(newT){
    case 1:
      StartTask(approach_light);
      break;
    case 0:
      StartTask(seek);
      break;
    }
  }
}

void stopCurrentTask(int oldT)
{
  switch(oldT){
    case 1:
      StopTask(approach_light);
      break;
    case 0:
      StopTask(seek);
      break;
  }

}

task seek()
{
  int speed = 10;
  nSyncedMotors = synchAB;
  nSyncedTurnRatio = -100;
  motor[motorA] = speed;
}

task approach_light()
{
  float left = SensorValue(leftLight);
  float right = SensorValue(rightLight);
  float leftness = left - right;
  float powerConstant = 2;
  nSyncedMotors = synchAB;
  nSyncedTurnRatio = -100;
  motor[motorA] = -powerConstant*leftness;
}
