#pragma config(Sensor, S1,     sonar,               sensorSONAR)
#pragma config(Sensor, S2,     bump,                sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          sonarMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "circularScan.c"
#include "Utils.c"

int first;
int second;
int third;

int sonarOffset = 4;

const float ENC_P_CM = 21.157;
const int drive_power = 20;
const int wall_distance = 20;
const float damper = 0.25;

/* Global to fix memory error. */
loc_sig scan;

void getIntoCorridor()
{

  //Scan 360 and work out which array element is the largest sonar reading.

  //Make this so it rotates the robot!
  circularScan(scan);

  int result = -1;
  int boundary = 0;

  while(result == -1)
  {
    for(int i = 0 ; i < NO_BINS ; i++)
    {
      if(scan.sig[i] == (63 - sonarOffset + boundary) || scan.sig[i] == (63 - sonarOffset - boundary))
      {
        result = i;
      }
    }
    boundary++;
  }

  nxtDisplayCenteredTextLine(1, "ArrElt: %d", result);
  wait1Msec(1000);

  //Rotate so that you face that way.
  float turnAngle = (result / 180.0)*PI;

  nxtDisplayCenteredTextLine(2, "TurnAngle: %f", turnAngle);
  wait1Msec(1000);

  turnRadiansClockwise(turnAngle); //minus removed

  nSyncedMotors = synchAB;
  nSyncedTurnRatio = 100;
  motor[motorA] = 30;

  while(SensorValue[sonar] > 21 - sonarOffset)
  {

  }

  motor[motorA] = 0;

  //Scan 360 and work out which array element is the largest sonar reading.
  //Rotate so that you face that way.
  //Drive until you are 21 away from the wall infront (allow for sonar wheelbase offset)
}

int calculateCurrentWaypoint()
{
  nMotorEncoder[motorC] = 0;
  int waypoint = 0;

  //Turn the sonar right.
  motor[motorC] = -20;
  while(nMotorEncoder[motorC] > -90)
    ;

  if (SensorValue[sonar] < 50)
  {
    //fix and return
    motor[motorC] = 20;
    while(nMotorEncoder[motorC] < 0)
      ;
    motor[motorC] = 0;
    nMotorEncoder[motorC] = 0;
    return 1;
  }

  //Turn the sonar left.
  motor[motorC] = 20;
  while(nMotorEncoder[motorC] < 90)
    ;

  if (SensorValue[sonar] < 50)
  {
    waypoint = 3;
  } else {
    waypoint = 2;
  }

  //fix and return
  motor[motorC] = -20;
  while(nMotorEncoder[motorC] > 0)
    ;
  motor[motorC] = 0;
  nMotorEncoder[motorC] = 0;
  return waypoint;
}

void corridorTurn(int currentWaypoint, int destinationWaypoint)
{
  //Turn based on arguments.
  //Face sonar to the correct wall.

  nxtDisplayCenteredTextLine(4, "from: %d", currentWaypoint);
  nxtDisplayCenteredTextLine(5, "to: %d", destinationWaypoint);
  wait1Msec(1000);

  float a = 0;
  switch(currentWaypoint)
  {
    case 1:
      a = PI/2;
      break;
    case 2:
      a = (destinationWaypoint == 1) ? -PI/2 : PI/2;
      break;
    case 3:
      a = -PI/2;
      break;
  }
  turnRadiansClockwise(a);
}

void downCorridor(int from, int to)
{

  float distance = 252;
  float step = 20;

  float balance = 0;
  nMotorPIDSpeedCtrl[motorA] = mtrSpeedReg;
  nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg;
  float encoderLimit = ENC_P_CM*distance;

  if(to == 2) //THIS ISNT RIGHT... NEED TO TURN SONAR ETC.
  {
      nMotorEncoder[motorA] = 0;
		  while((nMotorEncoder[motorA]) < encoderLimit)
		  {
			    balance = damper*(SensorValue[S1] - wall_distance);
			    motor[motorA] = drive_power - balance;
			    motor[motorB] = drive_power + balance;
		  }
		  motor[motorA] = 0;
		  motor[motorB] = 0;
  }
  else
  {
      int sonarReading = SensorValue(sonar);
      while( sonarReading > (21 - sonarOffset) )
      {
         //Take sonar reading.

            sonarReading = SensorValue(sonar);
            nxtDisplayCenteredTextLine(6, "sonar: %d", sonarReading);



         //Turn sonar to face wall.
         if(to == 1)
         {
	           motor[motorC] = 10;
	           nMotorEncoder[motorC] = 0;
	           while(nMotorEncoder[motorC] < 90)
	           {

	           }
	           motor[motorC] = 0;
         }
         else //to == 3
         {
	           motor[motorC] = -10;
	           nMotorEncoder[motorC] = 0;
	           while(nMotorEncoder[motorC] > -90)
	           {

	           }
	           motor[motorC] = 0;
         }

         //Drive

         sonarReading = SensorValue(sonar);
         int driveDist = (step < sonarReading - (21 + sonarOffset)) ? step : sonarReading - 21;
         encoderLimit = ENC_P_CM*driveDist;
         nMotorEncoder[motorA] = 0;

         while((nMotorEncoder[motorA]) < encoderLimit)
		     {
					   balance = damper*(SensorValue[S1] - wall_distance);
					   motor[motorA] = drive_power - balance;
					   motor[motorB] = drive_power + balance;
					   wait1Msec(1000);
		     }
		     motor[motorA] = 0;
		     motor[motorB] = 0;

		     //Sonar forwards.

		     //Turn sonar to face away from wall.
         if(to == 1)
         {
	           motor[motorC] = -10;
	           nMotorEncoder[motorC] = 0;
	           while(nMotorEncoder[motorC] > -90)
	           {

	           }
	           motor[motorC] = 0;
         }
         else //to == 3
         {
	           motor[motorC] = 10;
	           nMotorEncoder[motorC] = 0;
	           while(nMotorEncoder[motorC] < 90)
	           {

	           }
	           motor[motorC] = 0;
         }
         sonarReading = SensorValue(sonar);

      }
  }
  //If the destination is waypoint 2 we need to train the odometry to drive
  //the correct distance whilst wall following.

  //Otherwise we need to wall follow and occasionaly shoot the sonar forwards
  //to gauage our depth from the wall infront. We want to stop at 21 from the
  //wall.
}

void turnToWaypoint(int previous, int dest)
{
  //Rotate to face the waypoint, for 1 and 3 this is dependent only on the
  //destination whereas for waypoint 2 we need to know where we came from.
    //Turn based on arguments.
  //Face sonar to the correct wall.
  float a = 0;
  switch(dest)
  {
    case 1:
      a = -PI/2;
      break;
    case 2:
      switch(previous)
      {
        case 1:
          a = PI/2;
          break;
        case 3:
          a = -PI/2;
          break;
      }
    case 3:
      a = PI/2;
      break;
  }
  turnRadiansClockwise(a);
}

void driveToBackWall()
{
  //Drive forwards till the sonar gives a reading of 21.

  nSyncedMotors = synchAB;
  nSyncedTurnRatio = 100;
  motor[motorA] = 30;
  while(SensorValue(sonar) > 21 - sonarOffset)
    ;
  motor[motorA] = 0;

}

void chamberAdjust()
{
  //Sonar look left + take reading.
  nMotorEncoder[motorC] = 0;
  motor[motorC] = 5;
  while(nMotorEncoder[motorC] < 90)
    ;
  motor[motorC] = 0;
  int leftReading = SensorValue(sonar);
  nxtDisplayCenteredTextLine(1, "LR: %d", leftReading);

  //Sonar look right + take reading.
  motor[motorC] = -5;
  while(nMotorEncoder[motorC] > -90)
    ;
  motor[motorC] = 0;
  int rightReading = SensorValue(sonar);
  nxtDisplayCenteredTextLine(2, "RR: %d", rightReading);


  wait1Msec(5000);
  //Recenter sonar
  motor[motorC] = 5;
  while(nMotorEncoder[motorC] < 0)
    ;
  motor[motorC] = 0;
  //Adjust the position of the robot so that the left reading = right reading.
  if(leftReading > rightReading)
  {
    turnRadiansClockwise(PI/2);
    nSyncedMotors = synchAB;
    nSyncedTurnRatio = 100;
    motor[motorA] = 5;
    while( SensorValue(sonar) > 21 - sonarOffset)
      ;
    motor[motorA] = 0;
    turnRadiansClockwise(-PI/2);
  }
  else if(leftReading < rightReading)
  {
    turnRadiansClockwise(-PI/2);
    nSyncedMotors = synchAB;
    nSyncedTurnRatio = 100;
    motor[motorA] = 5;
    while( SensorValue(sonar) > 21 - sonarOffset)
      ;
    motor[motorA] = 0;
    turnRadiansClockwise(PI/2);
  }

}

void beep()
{
  //beep when done.
  PlayImmediateTone(780, 100);
}

task main()
{
	getIntoCorridor();

	int currentWaypoint = calculateCurrentWaypoint();
	nxtDisplayCenteredTextLine(3, "WP: %d", currentWaypoint);
  wait1Msec(3000);

	if(currentWaypoint == 1)
	{
		first = 2;
		second = 3;
		third = 1;
	}
	else if(currentWaypoint == 2)
	{
		first = 3;
		second = 1;
		third = 2;
	}
	else //currentWaypoint == 3
	{
		first = 2;
		second = 1;
		third = 3;
	}

	/* First */
	corridorTurn(currentWaypoint, first);
	wait1Msec(5000);
	downCorridor(currentWaypoint, first);
	turnToWaypoint(currentWaypoint, first);
	driveToBackWall();
	chamberAdjust();
	beep();
	/* End First */

	/* Second */
	/*currentWaypoint = first;
	getIntoCorridor();
	corridorTurn(currentWaypoint, second);
	downCorridor(currentWaypoint, second);
	turnToWaypoint(currentWaypoint, second);
	driveToBackWall();
	*/ /*chamberAdjust();
	beep();*/
	/* End Second */

	/* Third */
	/*currentWaypoint = second;
	getIntoCorridor();
	corridorTurn(currentWaypoint, third);
	downCorridor(currentWaypoint, third);
	turnToWaypoint(currentWaypoint, third);
	driveToBackWall();
	chamberAdjust();
	beep();*/
	/* End Third */
}
