#pragma config(Sensor, S1,     sonar,               sensorSONAR)
#pragma config(Sensor, S2,     bump,                sensorTouch)
#pragma config(Motor,  motorA,          left,          tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          sonar,         tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/// Number of locations we want to learn in the environment
#define NO_LOCS 3

void resetSonar()
{
	nMotorEncoder[motorC] = 0;
	motor[motorC] = -20;
	while(nMotorEncoder[motorC] > -360)
	{

	}
	motor[motorC] = 0;
}

void face_forward()
{

  nSyncedMotors = synchAB;
  nSyncedTurnRatio = -100;
  motor[motorA] = 30;


  while(abs(SensorValue[sonar] - 57) > 2)
    ;


  motor[motorA] = 0;

}

task main()
{
  face_forward();
  return;
}
